// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://goicesirlbdgjspjpcin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvaWNlc2lybGJkZ2pzcGpwY2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mzg0NjAsImV4cCI6MjA3MDIxNDQ2MH0.gkaugQZEGsrhbIDuvOEGwbRuwPCI-EZoDRzA5iP3How";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);